### ISSUE TITLE
1.20（+）支持 TODO List

### ISSUE THREAD

**Issue by dovisutu** [CFPAOrg/Minecraft-Mod-Language-Package#3367]
### 详细信息

相比于#2821 而言，这次的时间应该没那么紧张。但是先列出来吧。
其中有一些可能不是马上就需要的，但是也先列出来吧。

- [ ] 确定1.20（或更高版本）的支持计划
- [ ] 建立1.20的预备分支，在工作完成后合并

### 文件结构/工作流程

- [ ] 正确书写文件层级，以及Packer的配置文件
- [ ] Github Actions 相关内容（Packer，PR-Packer，Label）
- [ ] ~bot支持~
  - 这个短期可能看不到了。
- [ ] i18n模组以及分发服务器的正确支持

### 资源包

- [ ] #2721 - #3226 - #3288 ：字体修复全面更新
  - 由于1.20去除了对legacy_unicode加载器的支持，这一点是必需的。
  - [ ] （可能需要）修改Packer，以将字符替换做成版本特定
    - 这个就做在3288里面了。
- 模组收录问题
  - [ ] 是否需要推行基于现行packer-policy的适配方案，或者优化方案？
    - 可能需要研究一下加载逻辑被执行两次的问题？（不过这个不重要）
  - [ ] 是否需要与现有的资源包合并机制协同？

### 文档相关
- [ ] #3178 - #2857 参考文档更新（可能需要更新）

**Comment by Slow-Witted-Fish** [comment]
> * [ ]  ~bot支持~

[支持1.20的bot](https://github.com/Slow-Witted-Fish/CFPABot/tree/master) 需要服务器，部署麻烦

**Comment by Cactusstudent** [comment]
>仍需找个人进行长期维护

这个需要人力，优先级低（

**Comment by dovisutu** [comment]
Packer系列单列表
（本来想列自己那边的，结果issue创不上了...）

---

Packer ToDo/Refact

- Meta
  - 局域配置文件
  - policy改写
- Models
  - 文件模型：转换为用抽象类`ResourceFile`（或者接口？），上面实现BypassedFile，TextFile，[Json, Lang]LanguageFile
  - 考量：是否要实现成Immutable？
  - 考量：两种LanguageFile应该继承TextFile存储原文，还是一律序列化成字典？
  - 考量：LanguageFile系列如何“优雅”地实现key-value字典？因为value表目前是Lang为string，json可能需要用JsonElement才能避免一堆奇怪的文件
    - 还有暴力的做法就是干脆出错就回退TextFile...
  - 暴露方法/字段：
    - `void AddTo(ZipArchive archive, ...); // 加入文件`
    - `void Append(IResourceFile incoming, bool overrideExisting = false); // 合并文件`；可能只对[]LanguageFile有真的适配；或者说，要不写成重载运算符operator+得了...
    - `public string Destination { get; init { /* normalize */ } } // 资源包中的目标地址`
- Lib.cs（检索组件a）- 正统的Linq检索语法
  - 生成的应当是`IEnumerable<IResourceFile>`；中间的Mod和Asset信息应当可用typed Tuple？
  - `Groupby(_ => _.Destination).Select(_ => _.Keys.<...) // 排重空间`；还是Distinct？
  - `Where(_ => _ in acceptedModsList ?? true) // 传参支持`
- Extensions/DirectoryExtension.cs（检索组件b - policy）
  - 将加载方案改成依次执行可覆盖
    - 用`Delegate`的多播应该可实现；更好的是，我似乎不需要ref了！（逃
- Config
  - 新增项：forceInclude，asNonText，？？

**Comment by Cactusstudent** [comment]
对 packer 的建议：可以再重新设计 Packer 的打包逻辑，不然一到后期支持版本多起来了一遍遍过确实是太过于浪费时间了

**Comment by dovisutu** [comment]
> 不然一到后期支持版本多起来了一遍遍过确实是太过于浪费时间了

如果我没写错的话，现在Packer和PR-Packer好像都是只打包被更改的版本吧
（还是我没理解清楚？）

**Comment by Cactusstudent** [comment]
> 如果我没写错的话，现在Packer和PR-Packer好像都是只打包被更改的版本吧 （还是我没理解清楚？）

我的表达问题，实则想表达的是**想让打包的文件中只包含更改的一个或几个模组**，不然 Upload 这一条耗得时间就太长了。（例：若PR中同时更改了1.16 1.18两个版本的汉化文件，一整个流程走下来得六七分钟，过于耗费时间了。

**Comment by dovisutu** [comment]
> 想让PR-packer打包的文件中只包含更改的一个或几个模组

~巧了，这个我也做了~

目前逻辑是，如果改了打包器/配置，pr-packer会打包某版本的所有文件；否则，只打包被更改的**模组**。（因为不好判断配置等会改变哪些文件，只有全部打包。）
然后3875“恰好”更改了打包器和配置，这就提现不出来了。

packer肯定还是要全部打包的。

**Comment by Cactusstudent** [comment]
TODO：
- [ ] 排查清楚 1.20 的双加载器的资源包在服务器上是有时无的问题并尽快解决
